### ISSUE TITLE
Carousel minor bugs

### ISSUE THREAD

**Issue by alvinleung** [daybreak-studio/superpower#9]
- Currently unable to control scroll when the user scrolling through the area, possibly make the horizontal swipe detection less aggressive (look into the pointer down rejection state). 

![IMG_4026](https://github.com/daybreak-studio/superpower/assets/757283/c22db6a7-91b1-4d51-87a0-317011d2826a)

- Also the wheel event is currently bounded to window object instead of the local div, making when the user scroll horizontally, all instances on the page will move at the same time, which is not ideal. They should be moved individually.

**Comment by christopher-ha** [comment]
Feedback in #10 mentions this
